modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="yummy_treats"
version="1.0.0"
displayName="Yummy Treats"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="reube, MCreator"

[[dependencies.yummy_treats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




