modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="yummy_treats"
version="1.0.0"
displayName="Yummy Treats"
credits="Copyrights 2020 Reuben Schiopu"
displayURL="https://mcreator.net"
authors="MangoCoder360"

[[dependencies.yummy_treats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




